### PR TITLE
bumping nltk to 2.0.5 - see #824 in nltk

### PR DESCRIPTION
**Pull request by hexelon**
This has to be done due to https://github.com/nltk/nltk/issues/824

### CODE REVIEW

**Comment by jwarzech** [comment]
+1 please pull this in as soon as you get a chance :)

**Comment by codelucas** [comment]
Thanks for the PR guys! :+1: We should probably bump up the py3 nltk requirement to 3.0.1 as well ..

**Comment by jwarzech** [comment]
Thanks!  When do you think you will do a release with this change?

**Comment by codelucas** [comment]
A release should be out (for both py2 and py3) tonight! I'll update this thread when it's done.

**Comment by codelucas** [comment]
New versions of newspaper are pushed live into pypi! Your pip installations should be working now.

Thanks so much for catching this early

**Pull request merged**
