### PR TITLE
Is newspaper3k running on python 3.6 ?

### PR DESCRIPTION
**Pull request by hartym**

### CODE REVIEW

**Comment by hartym** [comment]
Ref to problem : http://www.psf.upfronthosting.co.za/issue28450

Traceback : 

`
Traceback (most recent call last):
  File "tests/unit_tests.py", line 25, in <module>
    import newspaper
  File "/Users/rd/Projects/newspaper/tests/../newspaper/__init__.py", line 10, in <module>
    from .article import Article, ArticleException
  File "/Users/rd/Projects/newspaper/tests/../newspaper/article.py", line 13, in <module>
    from . import network
  File "/Users/rd/Projects/newspaper/tests/../newspaper/network.py", line 14, in <module>
    from .configuration import Configuration
  File "/Users/rd/Projects/newspaper/tests/../newspaper/configuration.py", line 15, in <module>
    from .parsers import Parser
  File "/Users/rd/Projects/newspaper/tests/../newspaper/parsers.py", line 20, in <module>
    from . import text
  File "/Users/rd/Projects/newspaper/tests/../newspaper/text.py", line 59, in <module>
    class StopWords(object):
  File "/Users/rd/Projects/newspaper/tests/../newspaper/text.py", line 62, in StopWords
    "[^\\p{Ll}\\p{Lu}\\p{Lt}\\p{Lo}\\p{Nd}\\p{Pc}\\s]")
  File "/Users/rd/.envs/bb/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/rd/.envs/bb/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/rd/.envs/bb/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/rd/.envs/bb/lib/python3.6/sre_parse.py", line 856, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
  File "/Users/rd/.envs/bb/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/Users/rd/.envs/bb/lib/python3.6/sre_parse.py", line 526, in _parse
    code1 = _class_escape(source, this)
  File "/Users/rd/.envs/bb/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
`

**Comment by hartym** [comment]
Looks like the constant which cause the error is just unused in the whole package. I did not understand hat it was supposed to do, but unless there are external things using this stuff I suppose it's safe to remove.

**Comment by codelucas** [comment]
Wow this was not importing in 3.6? Thanks for fixing!

**Comment by codelucas** [comment]
Issue #315

**Pull request merged**
