### PR TITLE
fix for "jpeg error with PIL, Can't convert 'NoneType' object to str implicitly"

### PR DESCRIPTION
**Pull request by kotrfa**
Fix for an issue [#95](https://github.com/codelucas/newspaper/issues/95). I'm not sure with that, but it works for me and test passed.

### CODE REVIEW

**Comment by adrienthiery** [comment]
@codelucas Would love to see this PR merged if it seems relevant, this error is messing with my logs :/

Love newspaper anyway ! Great job

**Comment by codelucas** [comment]
It's been merged, I apologize for being so inactive recently

**Comment by codelucas** [comment]
The new module hasn't been pushed in pypi, you're all going to have to pull from master for the meantime

**Comment by kotrfa** [comment]
:+1:

**Comment by adrienthiery** [comment]
Thanks ! :+1:

**Pull request merged**
