### PR TITLE
Parse byline fix

### PR DESCRIPTION
**Pull request by davecrumbacher**
I found a couple cases where the author was not getting extracted correctly:
 * If the name has a period in it, e.g. Tyler G. Jones, it drops the last name (Tyler G.)
 * If the name is hyphenated, e.g. Jessica Silver-Greenberg, it would not capitalize the last name (Jessica Silver-greenberg)

This pull request addresses both of these issues.  Thanks.

### CODE REVIEW

**Comment by davecrumbacher** [comment]
It looks like a test is failing, so I am closing this for now.  Will re-open and include changes to tests after I've resolved it.

**Comment by codelucas** [comment]
:+1: Thanks for the PR anyways, looking forward to the updated version

**Comment by davecrumbacher** [comment]
Okay, I have made some more changes, including the tests.  I modified the sample HTML file to include a more complex list of authors.  The tests are passing, but please comment if you see any potential troubles with this approach.

**Comment by codelucas** [comment]
Merged finally, thanks for this!

**Pull request merged**
