### PR TITLE
Python 2 -  update requirements and wrong format of log message

### PR DESCRIPTION
**Pull request by korycins**

### CODE REVIEW

**Comment by korycins** [comment]
@codelucas  Can you take a look? It would be great to fix one log message and update requirements

**Comment by codelucas** [comment]
Hey @korycins, thanks so much for this great work! 👍 💯 It actually fixes a few bugs but I was looking at the bugs earlier and forgot about this PR. Ive already sent fixes for the requirements.txt and the new .travis.yml for the python2 branch. Can you remove those parts (fix merge conflict) and then I can approve this and merge it (your fixes to the log msg and test are good, we need them).

Thanks

**Comment by codelucas** [comment]
Closing for now until changes are made

**Comment by korycins** [comment]
@codelucas Sorry for late response. I had a lot of tasks to do at the end of the year. 
I created new PR as you requested only for wrong log message
Please see PR: #498

**Pull request closed without merging**
