### PR TITLE
Travis CI integration

### PR DESCRIPTION
**Pull request by yprez**
Add the basic .travis.yml file to run the tests on several versions of Python after every commit, PR, etc.
This might also help with the requirements versions breaking when upgraded...

@codelucas All you need to do to enable this is to sign up to to http://travis-ci.org/ (if you don't already have an account) and enable this repo.

And added badge in the readme like: https://travis-ci.org/yprez/newspaper.svg?branch=travis : 

Hope this is useful...

### CODE REVIEW

**Comment by yprez** [comment]
Actually it shows the tests are passing when some are actually failing - I'll take a look and reopen when it's resolved.

**Comment by yprez** [comment]
Works fine now.

There are some issues on running Python 3.5 (I disabled it for now) and #179 seems to break this build, so it's probably better to merge this one first...

**Comment by yprez** [comment]
Build history for my branch: https://travis-ci.org/yprez/newspaper/builds

**Comment by codelucas** [comment]
Wow, great work. Merging and also creating the travis CI for this

**Comment by yprez** [comment]
@codelucas you just need to enable it here: https://travis-ci.org/profile/

**Comment by codelucas** [comment]
@yprez It's been enabled!

**Comment by codelucas** [comment]
@yprez: Our build is passing: https://travis-ci.org/codelucas/newspaper

**Comment by yprez** [comment]
:+1:

**Pull request merged**
